name: Run pre-commit

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  pre-commit:
    permissions:
      contents: read
    uses: cpp-linter/.github/.github/workflows/pre-commit.yml@main
